- db_info:
    sqlnosql: NoSQL
    dbms: mongodb
    username: root
    password: password
    database: Squaddb
    host: localhost
    port: 27017
    proto_folder: proto
    router_path: C:\_dev\shiftschedulerback\app\routes
    googleapis_path: C:\Users\kateb\go\pkg\mod\github.com\grpc-ecosystem\grpc-gateway@v1.16.0\third_party\googleapis
    api: /v1/